# Generated by Django 2.2.7 on 2019-12-08 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocab',
            options={},
        ),
    ]
