# Generated by Django 2.2.7 on 2020-01-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_auto_20191218_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vocab',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vtype',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
