# Generated by Django 2.2.7 on 2020-01-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0004_myphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myphoto',
            name='title',
        ),
    ]
