# Generated by Django 2.2.7 on 2020-01-04 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myphoto',
            name='lnote',
        ),
        migrations.DeleteModel(
            name='LNote',
        ),
        migrations.DeleteModel(
            name='MyPhoto',
        ),
    ]
